clone_folder: "c:\\network-bug"

install:
- ps: |
    Invoke-WebRequest "https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-windows.zip" -OutFile stack.zip

    Invoke-WebRequest "https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-windows.zip" -OutFile stack.zip
    Invoke-WebRequest "https://github.com/fpco/minghc/blob/master/bin/7z.exe?raw=true" -OutFile 7z.exe
    Invoke-WebRequest "https://github.com/fpco/minghc/blob/master/bin/7z.dll?raw=true" -OutFile 7z.dll
    7z x stack.zip
    move stack.exe.exe stack.exe
    $env:Path += "; $(get-location)"
- ps: |
    cd C:\\network-bug
    stack setup
    stack build
- ps: |
    $env:Path += "; C:\network-bug\.stack-work\install\i386-windows\ghc-7.10.1\7.10.1\bin"
    network-bug.exe
    echo "" | stack exec -- runhaskell src/Main.hs

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack exec -- runhaskell src/Main.hs